/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-07 10:27:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class docBao_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row space  w-80\">\r\n");
      out.write("			<div class=\"col-lg-8\">\r\n");
      out.write("				<div class=\"dateTime\">\r\n");
      out.write("					<label>Thứ năm, 7/12/2023, 13:35(GMT+7)</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"title\">\r\n");
      out.write("					<label>Thủ tướng Campuchia Hun Manet sắp thăm Việt Nam</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"descrip\">\r\n");
      out.write("					<label>Thủ tướng Campuchia Hun Manet sẽ thăm chính thức\r\n");
      out.write("						Việt Nam vào tuần sau theo lời mời của Thủ tướng Phạm Minh Chính.\r\n");
      out.write("\r\n");
      out.write("						Chuyến thăm của Thủ tướng Campuchia sẽ diễn ra ngày 11-12/12, theo\r\n");
      out.write("						thông cáo Bộ Ngoại giao. Đây là lần đầu tiên Thủ tướng Hun Manet\r\n");
      out.write("						thăm Việt Nam từ khi ông nhậm chức hồi tháng 8.</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<img alt=\"\"\r\n");
      out.write("						src=\"https://i1-vnexpress.vnecdn.net/2023/12/07/33UA3N7-highres-4432-1701939664.jpg?w=1020&h=0&q=100&dpr=1&fit=crop&s=QJvFBw_2gHBshIXSUPrtCA\"\r\n");
      out.write("						class=\"card-img\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"content\">\r\n");
      out.write("					<label>Phiên đấu giá ba mỏ cát do Sở Tài nguyên và Môi trường Hà Nội tổ chức diễn ra liên tục 21,5 tiếng ngày 5-6/11. Mỏ Châu Sơn với trữ lượng hơn 700.000 m3, tiền đặt cọc hơn 400 triệu đồng, giá khởi điểm 2,8 tỷ đồng, được 29 tổ chức đủ điều kiện tham gia đấu giá từ 9h đến 21h ngày 5/11. Qua 89 vòng, Sở Tài nguyên và Môi trường xác định được nhà đầu tư giành quyền khai thác mỏ cát với giá hơn 396 tỷ đồng, gấp 141 lần mức khởi điểm.\r\n");
      out.write("\r\n");
      out.write("Mỏ Liên Mạc trữ lượng gần 500.000 m3 cát, tiền cọc trên 300 triệu đồng, giá khởi điểm 2 tỷ đồng, được 28 tổ chức đủ điều kiện tham gia đấu giá từ 21h ngày 5 đến 2h29 ngày 6/11. Qua 53 vòng, một doanh nghiệp giành quyền khai thác với giá 408 tỷ đồng, gấp 204 lần giá khởi điểm.\r\n");
      out.write("\r\n");
      out.write("Mỏ Tây Đằng - Minh Châu trữ lượng 4,9 triệu m3 cát, tiền cọc 2,8 tỷ đồng, giá khởi điểm hơn 19 tỷ đồng được 16 tổ chức tham gia đấu giá từ 2h30 đến 5h33 ngày 6/11. Qua 21 vòng, Sở Tài nguyên và Môi trường xác định được nhà đầu tư giành quyền khai thác với giá trúng hơn 880 tỷ đồng, gấp 46 lần giá khởi điểm.\r\n");
      out.write("\r\n");
      out.write("Tổng số tiền nhà đầu tư trúng đấu giá của ba mỏ cát gần 1.690 tỷ đồng, tiền đặt cọc 3,5 tỷ đồng, gấp 70 lần giá khởi điểm. Đơn vị giành quyền khai thác phải nộp đủ tiền theo thời gian quy định, nếu không sẽ mất tiền đặt cọc.\r\n");
      out.write("\r\n");
      out.write("Sau đó, Thủ tướng yêu cầu TP Hà Nội rà soát quá trình khảo sát, đánh giá trữ lượng, làm hồ sơ, tổ chức đấu giá cấp quyền khai thác mỏ cát bởi \"giá cao gấp nhiều lần giá khởi điểm, có yếu tố bất thường\". Hà Nội phải ngăn chặn hành vi lợi dụng đấu giá để đẩy giá, gây nhiễu loạn thị trường.</label>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4 ml-5\">\r\n");
      out.write("				<div class=\"list-group border sticky\">\r\n");
      out.write("					<span\r\n");
      out.write("						style=\"font-size: 20px; font-weight: bold; color: #9F224E; padding: 10px\">Xem\r\n");
      out.write("						nhiều</span> <a href=\"#\" class=\"list-group-item\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<img alt=\"\"\r\n");
      out.write("									src=\"https://i1-vnexpress.vnecdn.net/2023/12/06/VNEPlan-1701832660-8253-1701832713.jpg?w=300&h=180&q=100&dpr=1&fit=crop&s=VKgb_lY8XxyD6S-QVwdIAw\"\r\n");
      out.write("									class=\"card-img\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-8\">\r\n");
      out.write("								<label class=\"center\">Siêu tàu container chạy bằng lò\r\n");
      out.write("									phản ứng muối nóng chảy</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a> <a href=\"#\" class=\"list-group-item\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<img alt=\"\"\r\n");
      out.write("									src=\"https://i1-vnexpress.vnecdn.net/2023/12/06/VNEPlan-1701832660-8253-1701832713.jpg?w=300&h=180&q=100&dpr=1&fit=crop&s=VKgb_lY8XxyD6S-QVwdIAw\"\r\n");
      out.write("									class=\"card-img\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-8\">\r\n");
      out.write("								<label class=\"center\">Siêu tàu container chạy bằng lò\r\n");
      out.write("									phản ứng muối nóng chảy</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a> <a href=\"#\" class=\"list-group-item\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<img alt=\"\"\r\n");
      out.write("									src=\"https://i1-vnexpress.vnecdn.net/2023/12/06/VNEPlan-1701832660-8253-1701832713.jpg?w=300&h=180&q=100&dpr=1&fit=crop&s=VKgb_lY8XxyD6S-QVwdIAw\"\r\n");
      out.write("									class=\"card-img\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-8\">\r\n");
      out.write("								<label class=\"center\">Siêu tàu container chạy bằng lò\r\n");
      out.write("									phản ứng muối nóng chảy</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a> <a href=\"#\" class=\"list-group-item\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<img alt=\"\"\r\n");
      out.write("									src=\"https://i1-vnexpress.vnecdn.net/2023/12/06/VNEPlan-1701832660-8253-1701832713.jpg?w=300&h=180&q=100&dpr=1&fit=crop&s=VKgb_lY8XxyD6S-QVwdIAw\"\r\n");
      out.write("									class=\"card-img\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-8\">\r\n");
      out.write("								<label class=\"center\">Siêu tàu container chạy bằng lò\r\n");
      out.write("									phản ứng muối nóng chảy</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("				<a href=\"#\" class=\"list-group-item\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<img alt=\"\"\r\n");
      out.write("									src=\"https://i1-vnexpress.vnecdn.net/2023/12/06/VNEPlan-1701832660-8253-1701832713.jpg?w=300&h=180&q=100&dpr=1&fit=crop&s=VKgb_lY8XxyD6S-QVwdIAw\"\r\n");
      out.write("									class=\"card-img\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-8\">\r\n");
      out.write("								<label class=\"center\">Siêu tàu container chạy bằng lò\r\n");
      out.write("									phản ứng muối nóng chảy</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				<a href=\"#\" class=\"list-group-item\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<img alt=\"\"\r\n");
      out.write("									src=\"https://i1-vnexpress.vnecdn.net/2023/12/06/VNEPlan-1701832660-8253-1701832713.jpg?w=300&h=180&q=100&dpr=1&fit=crop&s=VKgb_lY8XxyD6S-QVwdIAw\"\r\n");
      out.write("									class=\"card-img\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-8\">\r\n");
      out.write("								<label class=\"center\">Siêu tàu container chạy bằng lò\r\n");
      out.write("									phản ứng muối nóng chảy</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	<div class=\"row space w-80\">\r\n");
      out.write("	<div class=\"col-lg-8\">\r\n");
      out.write("	<div class=\"comment\">\r\n");
      out.write("	<h3>Bình luận</h3>\r\n");
      out.write("	<textarea rows=\"7\" cols=\"\" wrap=\"soft\"></textarea>\r\n");
      out.write("	<button>Bình luận</button>\r\n");
      out.write("	 </div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
