/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-07 16:04:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-Avb2QiuDEEvB4bZJYdft2mNjVShBftLdPG8FJ0V7irTLQ8Uo0qcPxh4Plq7G5tGm0rU+1SPhVotteLpBERwTkw==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".label2 {\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	height: max-content;\r\n");
      out.write("	margin-top: auto;\r\n");
      out.write("	margin-bottom: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label2:hover .div2 {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".div2 {\r\n");
      out.write("	display: none;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	margin-top: 5px; /* Điều chỉnh khoảng cách giữa .label2 và .div2 */\r\n");
      out.write("	width: max-content;\r\n");
      out.write("	right: -120%;\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	border-color: #bebaba;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	padding-right: 20px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".div2::before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 15%;\r\n");
      out.write("	top: -10%;\r\n");
      out.write("	height: 15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav {\r\n");
      out.write("	position: sticky;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	font-size: 200%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 1060px) {\r\n");
      out.write("	.nav {\r\n");
      out.write("		display: none; /* Ẩn khi màn hình có chiều rộng tối đa là 600px */\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-item {\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	width: max-content;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-item:hover .nav-itemlist {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-itemlist {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	display: none;\r\n");
      out.write("	width: max-content;\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	border-color: gray;\r\n");
      out.write("	background-color: #932048e8;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-itemlist a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("	padding-left: 15px;\r\n");
      out.write("	padding-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	margin-right: 5%;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search input {\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("/* 	margin: auto; */\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("}\r\n");
      out.write(".search i {\r\n");
      out.write("margin-right: 0}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div\r\n");
      out.write("		style=\"display: flex; margin: 0 10% 0 10%; justify-content: space-between;\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<a href=\"\" style=\"display: block; height: max_content;\"><img\r\n");
      out.write("				alt=\"logo\"\r\n");
      out.write("				src=\"https://tse4.mm.bing.net/th?id=OIP._IfEaUssjZQwZ1u92b1_GgHaEK&pid=Api&P=0&h=180\"\r\n");
      out.write("				style=\"max-height: 100px\"> </a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"search\">\r\n");
      out.write("			<input type=\"text\"> <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"margin-top: auto; margin-bottom: auto; display: flex; width: max-content; justify-content: space-between;\">\r\n");
      out.write("			<a href=\"dangNhap.jsp\"\r\n");
      out.write("				style=\"padding: 12px; font-size: 20px; border-radius: 7px; color: white; font-weight: 600; background: #363628ed; text-decoration: none; text-align: center; margin-right: 20px;\">Đăng\r\n");
      out.write("				nhập</a> <a href=\"dangKy.jsp\"\r\n");
      out.write("				style=\"padding: 12px; font-size: 20px; border-radius: 7px; color: white; font-weight: 600; background: #363628ed; text-decoration: none; text-align: center;\">Đăng\r\n");
      out.write("				ký</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"label2\" style=\"display: none\">\r\n");
      out.write("			<label>Xin chào ...</label>\r\n");
      out.write("			<div class=\"div2\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"dangBai.jsp\"\r\n");
      out.write("						style=\"text-decoration: none; color: black;\">Đăng bài</a></li>\r\n");
      out.write("					<li><a href=\"\" style=\"text-decoration: none; color: black;\">Thông\r\n");
      out.write("							tin tài khoản</a></li>\r\n");
      out.write("					<li><a href=\"\" style=\"text-decoration: none; color: black;\">Thay\r\n");
      out.write("							đổi thông tin</a></li>\r\n");
      out.write("					<li><a href=\"\" style=\"text-decoration: none; color: black;\">Đổi\r\n");
      out.write("							mật khẩu</a></li>\r\n");
      out.write("					<li style=\"height: 1px; margin: 0; list-style: none;\"><hr\r\n");
      out.write("							class=\"\"></li>\r\n");
      out.write("					<li><a href=\"\"\r\n");
      out.write("						style=\"text-decoration: none; color: black; margin-top: 10px\">Đăng\r\n");
      out.write("							xuất</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("	<div class=\"nav\">\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\" style=\"padding: 15px;\"><i class=\"fa-solid fa-house\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\">Thời sự</a>\r\n");
      out.write("			<div class=\"nav-itemlist\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">Chính trị</a></li>\r\n");
      out.write("					<li><a href=\"\">Lao động</a></li>\r\n");
      out.write("					<li><a href=\"\">Giáo dục</a></li>\r\n");
      out.write("					<li><a href=\"\">Giao thông</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\">Thế giới</a>\r\n");
      out.write("			<div class=\"nav-itemlist\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">Tư liệu</a></li>\r\n");
      out.write("					<li><a href=\"\">Cuộc sống</a></li>\r\n");
      out.write("					<li><a href=\"\">Quân sự</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\">Kinh doanh</a>\r\n");
      out.write("			<div class=\"nav-itemlist\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">Quốc tế</a></li>\r\n");
      out.write("					<li><a href=\"\">Doanh nghiệp</a></li>\r\n");
      out.write("					<li><a href=\"\">Chứng khoáng</a></li>\r\n");
      out.write("					<li><a href=\"\">Bảo hiểm</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\">Bất động sản</a>\r\n");
      out.write("			<div class=\"nav-itemlist\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">Chính sách</a></li>\r\n");
      out.write("					<li><a href=\"\">Thị trường</a></li>\r\n");
      out.write("					<li><a href=\"\">Dự án</a></li>\r\n");
      out.write("					<li><a href=\"\">Tư vấn</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\">Thể thao</a>\r\n");
      out.write("			<div class=\"nav-itemlist\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">Bóng đá</a></li>\r\n");
      out.write("					<li><a href=\"\">Lịch thi đấu</a></li>\r\n");
      out.write("					<li><a href=\"\">Tennis</a></li>\r\n");
      out.write("					<li><a href=\"\">Marathon</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\">Giáo dục</a>\r\n");
      out.write("			<div class=\"nav-itemlist\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">Tin tức</a></li>\r\n");
      out.write("					<li><a href=\"\">Tuyển sinh</a></li>\r\n");
      out.write("					<li><a href=\"\">Du học</a></li>\r\n");
      out.write("					<li><a href=\"\">Học tiếng Anh</a></li>\r\n");
      out.write("					<li><a href=\"\">Giáo dục 4.0</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\">Đời sống</a>\r\n");
      out.write("			<div class=\"nav-itemlist\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">Nhịp sống</a></li>\r\n");
      out.write("					<li><a href=\"\">Tổ ấm</a></li>\r\n");
      out.write("					<li><a href=\"\">Cooking</a></li>\r\n");
      out.write("					<li><a href=\"\">Tiêu dùng</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\">Du lịch</a>\r\n");
      out.write("			<div class=\"nav-itemlist\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">Điểm đến</a></li>\r\n");
      out.write("					<li><a href=\"\">Ăm thực</a></li>\r\n");
      out.write("					<li><a href=\"\">Cẩm nang</a></li>\r\n");
      out.write("					<li><a href=\"\">Tư vấn</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-item\">\r\n");
      out.write("			<a href=\"\">Xe</a>\r\n");
      out.write("			<div class=\"nav-itemlist\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">Thị trường</a></li>\r\n");
      out.write("					<li><a href=\"\">Diễn đàn</a></li>\r\n");
      out.write("					<li><a href=\"\">Thi bằng lái</a></li>\r\n");
      out.write("					<li><a href=\"\">Mu bán</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- end navbar -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
